# Generated by Django 4.2.20 on 2025-09-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Tên sản phẩm')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Đường dẫn')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Mã sản phẩm')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
