# Generated by Django 4.2.20 on 2025-09-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='origin_price',
            field=models.FloatField(blank=True, default=0, verbose_name='Giá gốc'),
        ),
    ]
