# Generated by Django 4.2.20 on 2025-09-08 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Tên loại biến thể')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên biến thể')),
                ('v_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product.varianttype', verbose_name='Loại biến thể')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_diff', models.FloatField(blank=True, default=0, verbose_name='Giá thay đổi')),
                ('available', models.BooleanField(default=True, verbose_name='Còn hàng')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='product.product', verbose_name='Sản phẩm')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='product.variant', verbose_name='Biến thể')),
            ],
            options={
                'unique_together': {('product', 'variant')},
            },
        ),
    ]
