# Generated by Django 4.2.20 on 2025-09-09 07:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_productvariant_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Hình ảnh'),
        ),
    ]
